[package]
authors = [""]
compiler_version = "0.10.0"
#type = "lib"
type = "bin"
name = "linear_algebra"

[dependencies]
array_helpers = { tag = "v0.10.0", git = "https://github.com/colinnielsen/noir-array-helpers" }